# Generated by Django 5.1.2 on 2024-11-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='gallery',
            new_name='img',
        ),
    ]
