# Generated by Django 5.1.2 on 2024-11-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_gallery_gallery_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
