# Generated by Django 5.1.2 on 2024-10-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('custom_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
