# Generated by Django 5.1.2 on 2024-10-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='media')),
                ('food_name', models.CharField(max_length=100)),
                ('food_info', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
